# Generated by Django 3.0.3 on 2020-02-23 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_photo_thumname_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 23, 10, 16, 46, 308013, tzinfo=utc)),
        ),
    ]
