# Generated by Django 3.0.3 on 2020-02-23 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200223_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.user_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 2, 23, 11, 6, 36, 50338, tzinfo=utc)),
        ),
    ]
